name: "webchronicle"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    develop:
      watch:
        - action: sync
          path: ./webchronicle
          target: /app/webchronicle
